### ISSUE TITLE
Rate limit handling on the server.

### ISSUE THREAD

**Issue by bswopes** [oapi/shieldsup#22]
We should monitor the rate limit / remaining requests and back off as we approach the limit (X-Rate-Limit-Remaining, X-Rate-Limit-Limit); currently we appear to only know after we have exceeded the limit. 

Also, a relevant error message could be displayed to the user.

https://dev.twitter.com/rest/public/rate-limiting

**Comment by bswopes** [comment]
Could just be an issue with my setup, but the server currently appears to exit when rate limit exceeded. Does this happen to anyone else?

```
Exception `Twitter::Error::TooManyRequests' at /var/lib/gems/1.9.1/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15 - Rate limit exceeded
W, [2015-06-04T08:02:30.388013 #20243]  WARN -- : ERR_TWITTER: Rate limited (472)
Exception `Errno::EPIPE' at ./server.rb:30 - Broken pipe
Exception `Errno::EPIPE' at ./server.rb:513 - Broken pipe
./server.rb:30:in `write': Broken pipe (Errno::EPIPE)
	from ./server.rb:30:in `puts'
	from ./server.rb:30:in `rescue in get_userdata'
	from ./server.rb:22:in `get_userdata'
	from ./server.rb:472:in `handle_client'
	from ./server.rb:520:in `block in main'
```

**Comment by bswopes** [comment]
On another rate limit exceeded, I found myself in a twitter auth loop. Discovered lots of duplicate tokens in the database, although the ID was set to 0 for all the dupes.

**Comment by wismer** [comment]
@bswopes my guess is a `UNIXSocket` is unceremoniously disconnecting, causing the broken pipe. 

Has a non-blocking approach been put forth, yet? I don't know php at all, unfortunately, so I don't know if it would be feasible or not to try implementing over the threading.

**Comment by bswopes** [comment]
I haven't seen that failure mode again. May need to die on just the right request.

This was the ruby server calling out to Twitter, btw, not the php frontend.

**Comment by freebsdgirl** [comment]
Eventually we'll be swapping between tokens on error, but we should probably do a better job of checking for errors. This is part of why there's a refresh in place on the web side - so we can wait for API limit to reset on the backend, until we've got enough tokens stored to actively swap between them.

**Comment by bswopes** [comment]
Did finally run into that error again. I'm thinking it may be only when the initial auth / get_userdata call fails, since I also had the server die on me like this:

```
Exception `OpenSSL::SSL::SSLError' at /usr/lib/ruby/1.9.1/openssl/buffering.rb:174 - read would block
Exception `Twitter::Error::Unauthorized' at /var/lib/gems/1.9.1/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15 - Invalid or expired token.
E, [2015-06-19T09:53:30.642702 #30153] ERROR -- : AUTH: Fail (Unauthorized)
Exception `Errno::EPIPE' at ./server.rb:26 - Broken pipe
Exception `Errno::EPIPE' at ./server.rb:513 - Broken pipe
./server.rb:26:in `write': Broken pipe (Errno::EPIPE)
	from ./server.rb:26:in `puts'
	from ./server.rb:26:in `rescue in get_userdata'
	from ./server.rb:22:in `get_userdata'
	from ./server.rb:472:in `handle_client'
	from ./server.rb:520:in `block in main'
```
